version: "3"

services:
  fastapi-ml:
    image: ozayr0116/fastapi-ml:slim     
    build:
        context: .
        dockerfile: Dockerfile
    
    ports:
      - 8000:8000

networks:
    default:
        driver: bridge
