apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Ml-Microservice-Cluster
  region: us-west-2

nodeGroups:
  - name: predictor
    instanceType: t2.micro
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        autoscaler: true