apiVersion: apps/v1
kind: Deployment
metadata:
  name: JOB_NAME-app
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
        - name: predictor-microservice
          image: ORGANISATION/JOB_NAME:BUILD_NUM
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 200m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /api/status
              port: 8000
              initialDelaySeconds: 5
              periodSeconds: 5
              successThreshold: 1
  